# Generated by Django 6.0.4 on 2026-04-25 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='processingsnapshot',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='processingsnapshot',
            name='country_code',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterUniqueTogether(
            name='processingsnapshot',
            unique_together={('visa_type', 'scraped_date', 'country_code')},
        ),
    ]
