# Generated by Django 6.0.4 on 2026-04-25 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_processingsnapshot_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visatype',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
